/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Cake;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-03-12T11:39:55.360Z")

@Validated
@Api(value = "cakes", description = "the cakes API")
@RequestMapping(value = "")
public interface CakesApi {

    @ApiOperation(value = "", nickname = "cakesGet", notes = "", response = Cake.class, responseContainer = "List", authorizations = {
        @Authorization(value = "cake_auth", scopes = {
            @AuthorizationScope(scope = "read:cakes", description = "read cakes")
            })
    }, tags={ "cake", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Cake.class, responseContainer = "List") })
    @RequestMapping(value = "/cakes",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Cake>> cakesGet();


    @ApiOperation(value = "", nickname = "cakesPost", notes = "", authorizations = {
        @Authorization(value = "cake_auth", scopes = {
            @AuthorizationScope(scope = "write:cakes", description = "modify cakes")
            })
    }, tags={ "cake", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation") })
    @RequestMapping(value = "/cakes",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> cakesPost(@ApiParam(value = "" ,required=true )  @Valid @RequestBody Cake body);

}
