/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.waracle.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-03-12T11:39:55.360Z")

@Validated
@Api(value = "default", description = "the default API")
@RequestMapping(value = "")
public interface DefaultApi {

    @ApiOperation(value = "", nickname = "rootGet", notes = "", tags = {"cake",})
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "successful operation")})
    @RequestMapping(value = "/",
            produces = {"text/html"},
            method = RequestMethod.GET)
    ResponseEntity<Void> rootGet();

}
